-- Baseline schema, derived from the Hibernate 6 schema export of the JPA entities
-- (dev.mstefanov.hms.model) and hand-cleaned: named constraints, indexes on FK columns.

create table custom_user (
    id                bigint generated by default as identity primary key,
    username          varchar(30)  not null,
    password          varchar(255) not null,
    first_name        varchar(20)  not null,
    last_name         varchar(20)  not null,
    salutation        varchar(255),
    birthday          date,
    registration_date timestamp(6) not null,
    rating            float(53),
    enabled           boolean      not null,
    constraint uk_custom_user_username unique (username)
);

create table role (
    id      bigint generated by default as identity primary key,
    name    varchar(255) not null,
    user_id bigint       not null,
    constraint fk_role_user foreign key (user_id) references custom_user (id)
);
create index idx_role_user_id on role (user_id);

create table status (
    id                 bigint generated by default as identity primary key,
    name               varchar(255) not null,
    status_description text         not null,
    constraint uk_status_name unique (name)
);

create table department (
    id          bigint generated by default as identity primary key,
    name        varchar(45)   not null,
    description varchar(4500) not null
);

create table departments_doctors (
    department_id bigint not null,
    doctor_id     bigint not null,
    constraint pk_departments_doctors primary key (department_id, doctor_id),
    constraint fk_departments_doctors_department foreign key (department_id) references department (id),
    constraint fk_departments_doctors_doctor foreign key (doctor_id) references custom_user (id)
);
create index idx_departments_doctors_doctor_id on departments_doctors (doctor_id);

create table appointment (
    id               bigint generated by default as identity primary key,
    doctor_id        bigint not null,
    patient_id       bigint not null,
    status_id        bigint not null,
    appointment_time timestamp(6),
    constraint fk_appointment_doctor foreign key (doctor_id) references custom_user (id),
    constraint fk_appointment_patient foreign key (patient_id) references custom_user (id),
    constraint fk_appointment_status foreign key (status_id) references status (id)
);
create index idx_appointment_doctor_id on appointment (doctor_id);
create index idx_appointment_patient_id on appointment (patient_id);
create index idx_appointment_status_id on appointment (status_id);

create table prescription (
    id                 bigint generated by default as identity primary key,
    doctor_id          bigint        not null,
    patient_id         bigint        not null,
    appointment_id     bigint,
    date               date          not null,
    prescription_notes varchar(2000) not null,
    constraint fk_prescription_doctor foreign key (doctor_id) references custom_user (id),
    constraint fk_prescription_patient foreign key (patient_id) references custom_user (id),
    constraint fk_prescription_appointment foreign key (appointment_id) references appointment (id)
);
create index idx_prescription_doctor_id on prescription (doctor_id);
create index idx_prescription_patient_id on prescription (patient_id);
create index idx_prescription_appointment_id on prescription (appointment_id);
